[package]
name = "contact-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
xdg = "^2.1"
nanoid = "0.4.0"
vcard_parser = { path = "/home/lm/code/vcard_parser" }
